// FunSIP routing script
//
// This script is called for each out-of-dialog or dialog-initiating SIP
// request. In-dialog requests (with a To-tag) are routed automatically by
// the proxy using Route headers per RFC3261 §16.
//
// Implicit handling (you do NOT script these):
//   - ACK retransmissions are absorbed by the INVITE server transaction.
//   - 100 Trying for INVITE is generated by the server transaction.
//   - When a CANCEL matches a pending INVITE server transaction, the SIP
//     stack responds 200 to the CANCEL, fans CANCEL out to every pending
//     INVITE branch (state Calling/Proceeding), and answers 487 to the
//     INVITE if no final response has been forwarded yet. The script only
//     sees orphan CANCELs (no matching INVITE) — those go through the
//     normal forwarding path below.

var DOMAIN = "localhost";

function onRequest(req) {

    if (req.method === "REGISTER") {
        if (!authenticate(DOMAIN)) return;
        fixContact();
        processRegister();
        return;
    }

    if (/^(INVITE|MESSAGE|SUBSCRIBE|NOTIFY|OPTIONS|INFO|UPDATE|REFER|PUBLISH|CANCEL)$/.test(req.method)) {

        // Authenticate requests originating from our domain. CANCEL cannot
        // carry meaningful credentials — challenging it is pointless and
        // most clients will not retry.
        if (req.method !== "CANCEL" && req.from && req.from.host === DOMAIN) {
            if (!authenticate(DOMAIN)) return;
        }

        var contacts = lookup();
        if (contacts && contacts.length > 0) {
            log("routing " + req.method + " to " + contacts[0].contact);
            proxy(contacts[0]);
        } else {
            log("no registration found for " + req.requestUri.full);
            sendResponse(404, "Not Found");
        }
        return;
    }

    log("rejecting unknown method: " + req.method);
    sendResponse(405, "Method Not Allowed");
}
